version: '3.4'

services:
  firstservice:
    image: ${DOCKER_REGISTRY-}firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    ports:
      - "5001:80"
 
  secondservice:
    image: ${DOCKER_REGISTRY-}secondservice
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    ports:
      - "5002:80"

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=review
    ports:
      - 5432:5432
  
  rabbitmq:
    image: masstransit/rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672  

